project:
  type: website
  output-dir: docs 

website:
  title: "Foundations of Data Science"
  sidebar:
    style: "floating"
    contents:
      - section: "Course Info"
        contents:
          - index.qmd
          - conventions.qmd
      - section: "Introduction to Python"
        contents:
          - lectures/1.qmd
          - lectures/2.qmd
          - lectures/3.qmd
          - lectures/4.qmd
          - lectures/5.qmd
          - lectures/6.qmd
      - section: "Applications"
        contents:
          - lectures/plotting.qmd
          - lectures/pandas_intro.qmd
          - lectures/pandas_grouping.qmd
          - lectures/numpy_vectors.qmd
          - lectures/numpy_matrices.qmd
          - lectures/similarity.qmd

format:
  html:
    theme: cosmo
    css: custom.css
    toc: true
    html-math-method: katex
    code-copy: true

editor: visual